improve container load/install

diff --git a/scripts/load_containers_cache b/scripts/load_containers_cache
--- a/scripts/load_containers_cache
+++ b/scripts/load_containers_cache
@@ -26,9 +26,15 @@ then
 
     # Podman loads file archive from cache and copy it in the local repository
     podman load < "$cache"
-
-    echo "Image : $image"
-
-    # Remove the cache
-    rm -rf "$cache"
+    
+    #check if image is in local repository
+    if podman images | grep "$image"
+    then
+        echo "Image $image loaded"
+        # Remove the cache
+        rm -rf "$cache"
+    else
+        echo "Error: image $image not loaded, an error occured."
+        exit 1
+    fi
 fi
